apiVersion: v1
kind: ReplicationController
metadata:
  name: kube-haproxy
  labels:
    app: kube-haproxy
    version: v1
spec:
  replicas: 1
  selector:
    app: kube-haproxy
    version: v1
  template:
    metadata:
      labels:
        app: kube-haproxy
        version: v1
    spec:
      containers:
      - image: aledbf/kube-haproxy:v0.0.1
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
            scheme: HTTP
          initialDelaySeconds: 30
          timeoutSeconds: 5
        name: haproxy
        ports:
        # All http services
        - containerPort: 80
          hostPort: 80
          protocol: TCP
        # nginx https
        - containerPort: 443
          hostPort: 8080
          protocol: TCP
        # haproxy stats
        - containerPort: 1936
          hostPort: 1936
          protocol: TCP
        resources: {}
